Testing: main

main:
	g++ -g -o testing -std=c++11 -D__CUDNN__ GlobalAvgPoolingTest.cpp ../Header/Shape.cpp ../Header/Data.cpp ../Header/Tensor.cpp ../Header/Operator.cpp ../Header/LossFunction.cpp ../Header/Optimizer.cpp ../Header/Layer.cpp ../Header/NeuralNetwork.cpp -lcudart -lcudnn
