Testing: main

main:
	g++ -g -o testing -std=c++11 -lcudart -lcudnn Convolution_With_MNIST_fc1.cpp ../Header/Shape.cpp ../Header/Data.cpp ../Header/Tensor.cpp ../Header/Operator.cpp ../Header/Objective.cpp ../Header/Optimizer.cpp ../Header/NeuralNetwork.cpp
